// Writes Apache config into the build output. Other servers ignore these files.
import { writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import config from '../astro.config.mjs';

const outDir = process.argv[2] ?? 'dist';
const base = (config.base ?? '/').replace(/\/?$/, '/');

const root = `# Generated by scripts/postbuild.mjs
ErrorDocument 404 ${base}404.html
Options -Indexes
AddDefaultCharset UTF-8
AddCharset UTF-8 .html .txt .xml .css .js .svg

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/css text/xml application/xml application/javascript text/javascript image/svg+xml
</IfModule>

<IfModule mod_brotli.c>
  AddOutputFilterByType BROTLI_COMPRESS text/html text/plain text/css text/xml application/xml application/javascript text/javascript image/svg+xml
</IfModule>

AddType image/avif .avif
AddType font/woff2 .woff2

<IfModule mod_headers.c>
  <FilesMatch "\\.(html|txt|xml)$">
    Header set Cache-Control "no-cache"
  </FilesMatch>
  <FilesMatch "\\.(png|svg|ico)$">
    Header set Cache-Control "public, max-age=604800"
  </FilesMatch>
  Header set X-Content-Type-Options "nosniff"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
</IfModule>
`;

const assets = `# Generated by scripts/postbuild.mjs — hashed files never change
<IfModule mod_headers.c>
  Header set Cache-Control "public, max-age=31536000, immutable"
</IfModule>
`;

writeFileSync(join(outDir, '.htaccess'), root);
if (existsSync(join(outDir, '_astro'))) writeFileSync(join(outDir, '_astro', '.htaccess'), assets);
console.log(`postbuild: wrote .htaccess files to ${outDir} (base ${base})`);
